### ISSUE TITLE
TR 조회할 때. . .

### ISSUE THREAD

**Issue by cyberprophet** [terapark/KOAStudio#1]
키움측에 보낼 데이터는 어떻게 처리하신건가요?

**Comment by teranum** [comment]
- 왼쪽tr항목 클릭했을때 해당 tr [input] 필드 내용을 오른쪽 프로퍼티창에 넣어주고
https://github.com/terapark/KOAStudio/blob/a935693e3414feddadc08353ccde2f9096cc5b87/src/KOAStudio/Business/UIRequest.cs#L76

- 오른쪽 프로퍼티창에서 조회버튼 클릭하면 프로퍼티창(datagrid) 값을 읽어 datagrid row개수만큼 SetInputValue 하고, CommRqData를 요청합니다
https://github.com/terapark/KOAStudio/blob/a935693e3414feddadc08353ccde2f9096cc5b87/src/KOAStudio/Business/UIRequest.cs#L412

- 요청후 수신된 이벤트에서 싱글데이터, 멀티데이터를 읽어 조회데이터창에 넣어주었어요
https://github.com/terapark/KOAStudio/blob/a935693e3414feddadc08353ccde2f9096cc5b87/src/KOAStudio/Business/ApiEvents.cs#L16

**Comment by cyberchacha** [comment]
<img width="272" alt="20230530_104128" src="https://github.com/terapark/KOAStudio/assets/134266635/3ac58563-9042-449d-a7ae-77148ea5e8b9">

**Comment by cyberchacha** [comment]
> <img alt="20230530_104128" width="272" src="https://user-images.githubusercontent.com/134266635/241827333-3ac58563-9042-449d-a7ae-77148ea5e8b9.png">

opt10001을 조회하려면 싱글데이터에 값들을 직접 입력해야된다는 말씀이시죠?

**Comment by teranum** [comment]
![이미지 002](https://github.com/terapark/KOAStudio/assets/79031840/a5000399-4c74-4f7e-bb2b-31e8e21262d2)

1: opt10001선택
2: 005930 입력(삼성전자 6자리 종목코드)
3: <조회>버튼 클릭

조회데이터 창에 삼성전자 주식기본정보 데이터가 수신되어 표시됩니다.
(사용방법은 키움증권 KOAStudio.exe와 꼭 같습니다)
