### ISSUE TITLE
혹시 이베스트 xingAPI도 사용해보셨나요?

### ISSUE THREAD

**Issue by cyberprophet** [terapark/KOAStudio#2]
xingAPI는 dll로 지원하는데 이거도 openAPI처럼 64bit에서 사용하도록 만드는게 가능할까요?

**Comment by teranum** [comment]
이베스트는 이용해 보지 못했어요, 
키움같이 ocx로 인터페이스를 지원하는 경우는 규약이 명백해 소스 몰라도 가능하지만, dll경우는 아마 안될걸로 생각됩니다.

**Comment by cyberprophet** [comment]
> 답변 감사합니다.
