### ISSUE TITLE
System.FormatException

### ISSUE THREAD

**Issue by FaltoGH** [terapark/KOAStudio#3]
Doing CommRqData without any arguments cause the following exception:

응용 프로그램: KOAStudio.exe
Framework 버전: v4.0.30319
설명: 처리되지 않은 예외로 인해 프로세스가 종료되었습니다.
예외 정보:System.FormatException
   위치: System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
   위치: System.Number.ParseInt32(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   위치: System.Convert.ToInt32(System.String)
   위치: KOAStudio.Business.BusinessLogic.QueryApiAction(System.String, System.Object, Boolean)
   위치: KOAStudio.Core.ViewModels.PropertyViewModel.Query(Boolean)
   위치: CommunityToolkit.Mvvm.Input.RelayCommand`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Execute(Boolean)
   위치: CommunityToolkit.Mvvm.Input.RelayCommand`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Execute(System.Object)
   위치: MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource, Boolean)
   위치: System.Windows.Controls.Primitives.ButtonBase.OnClick()
   위치: System.Windows.Controls.Button.OnClick()
   위치: System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   위치: System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   위치: System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   위치: System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   위치: System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   위치: System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   위치: System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   위치: System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   위치: System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   위치: System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   위치: System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   위치: System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   위치: System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   위치: System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   위치: System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   위치: System.Windows.Input.InputManager.ProcessStagingArea()
   위치: System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   위치: System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   위치: System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   위치: System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   위치: System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   위치: MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   위치: MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   위치: System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   위치: MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   위치: MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   위치: System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   위치: System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   위치: System.Windows.Application.RunDispatcher(System.Object)
   위치: System.Windows.Application.RunInternal(System.Windows.Window)
   위치: System.Windows.Application.Run(System.Windows.Window)
   위치: KOAStudio.App.Main()

**Comment by teranum** [comment]
오류 발견 감사합니다.
![image](https://github.com/terapark/KOAStudio/assets/79031840/8c9e2aae-fdb2-4afd-84df-b7cab49f4078)
nPrevNext값을 삭제하고 빈문자열 또는 숫자아닌 문자로 요청시 오류 발생합니다.
아마도 다른 함수호출에서도 같은 오류가 발생될것 같어요
UIRequest.cs/QueryApiAction 함수내 Convert.ToInt32호출에서 입력값오류로 발생됩니다.
try/catch로 변환오류 잡아주면 될것 같어요
다음 커밋에 오류수정 반영할게요, 감사합니다.
